// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: transcode/v1/tasks.proto

package transcodev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranscodeStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscodeStart) Reset() {
	*x = TranscodeStart{}
	mi := &file_transcode_v1_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeStart) ProtoMessage() {}

func (x *TranscodeStart) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_v1_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeStart.ProtoReflect.Descriptor instead.
func (*TranscodeStart) Descriptor() ([]byte, []int) {
	return file_transcode_v1_tasks_proto_rawDescGZIP(), []int{0}
}

type TranscodeStop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscodeStop) Reset() {
	*x = TranscodeStop{}
	mi := &file_transcode_v1_tasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeStop) ProtoMessage() {}

func (x *TranscodeStop) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_v1_tasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeStop.ProtoReflect.Descriptor instead.
func (*TranscodeStop) Descriptor() ([]byte, []int) {
	return file_transcode_v1_tasks_proto_rawDescGZIP(), []int{1}
}

type TranscodeHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscodeHeartbeat) Reset() {
	*x = TranscodeHeartbeat{}
	mi := &file_transcode_v1_tasks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscodeHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscodeHeartbeat) ProtoMessage() {}

func (x *TranscodeHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_transcode_v1_tasks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscodeHeartbeat.ProtoReflect.Descriptor instead.
func (*TranscodeHeartbeat) Descriptor() ([]byte, []int) {
	return file_transcode_v1_tasks_proto_rawDescGZIP(), []int{2}
}

var File_transcode_v1_tasks_proto protoreflect.FileDescriptor

const file_transcode_v1_tasks_proto_rawDesc = "" +
	"\n" +
	"\x18transcode/v1/tasks.proto\x12\ftranscode.v1\"\x10\n" +
	"\x0eTranscodeStart\"\x0f\n" +
	"\rTranscodeStop\"\x14\n" +
	"\x12TranscodeHeartbeatBFZDkoftamainee.dev/project-horizon/gopkg/proto/transcode/v1;transcodev1b\x06proto3"

var (
	file_transcode_v1_tasks_proto_rawDescOnce sync.Once
	file_transcode_v1_tasks_proto_rawDescData []byte
)

func file_transcode_v1_tasks_proto_rawDescGZIP() []byte {
	file_transcode_v1_tasks_proto_rawDescOnce.Do(func() {
		file_transcode_v1_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transcode_v1_tasks_proto_rawDesc), len(file_transcode_v1_tasks_proto_rawDesc)))
	})
	return file_transcode_v1_tasks_proto_rawDescData
}

var file_transcode_v1_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_transcode_v1_tasks_proto_goTypes = []any{
	(*TranscodeStart)(nil),     // 0: transcode.v1.TranscodeStart
	(*TranscodeStop)(nil),      // 1: transcode.v1.TranscodeStop
	(*TranscodeHeartbeat)(nil), // 2: transcode.v1.TranscodeHeartbeat
}
var file_transcode_v1_tasks_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_transcode_v1_tasks_proto_init() }
func file_transcode_v1_tasks_proto_init() {
	if File_transcode_v1_tasks_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transcode_v1_tasks_proto_rawDesc), len(file_transcode_v1_tasks_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transcode_v1_tasks_proto_goTypes,
		DependencyIndexes: file_transcode_v1_tasks_proto_depIdxs,
		MessageInfos:      file_transcode_v1_tasks_proto_msgTypes,
	}.Build()
	File_transcode_v1_tasks_proto = out.File
	file_transcode_v1_tasks_proto_goTypes = nil
	file_transcode_v1_tasks_proto_depIdxs = nil
}
