// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vod/v1/events.proto

package vodv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VodAssemble struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VodAssemble) Reset() {
	*x = VodAssemble{}
	mi := &file_vod_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VodAssemble) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VodAssemble) ProtoMessage() {}

func (x *VodAssemble) ProtoReflect() protoreflect.Message {
	mi := &file_vod_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VodAssemble.ProtoReflect.Descriptor instead.
func (*VodAssemble) Descriptor() ([]byte, []int) {
	return file_vod_v1_events_proto_rawDescGZIP(), []int{0}
}

type VodReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VodReady) Reset() {
	*x = VodReady{}
	mi := &file_vod_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VodReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VodReady) ProtoMessage() {}

func (x *VodReady) ProtoReflect() protoreflect.Message {
	mi := &file_vod_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VodReady.ProtoReflect.Descriptor instead.
func (*VodReady) Descriptor() ([]byte, []int) {
	return file_vod_v1_events_proto_rawDescGZIP(), []int{1}
}

var File_vod_v1_events_proto protoreflect.FileDescriptor

const file_vod_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x13vod/v1/events.proto\x12\x06vod.v1\"\r\n" +
	"\vVodAssemble\"\n" +
	"\n" +
	"\bVodReadyB:Z8koftamainee.dev/project-horizon/gopkg/proto/vod/v1;vodv1b\x06proto3"

var (
	file_vod_v1_events_proto_rawDescOnce sync.Once
	file_vod_v1_events_proto_rawDescData []byte
)

func file_vod_v1_events_proto_rawDescGZIP() []byte {
	file_vod_v1_events_proto_rawDescOnce.Do(func() {
		file_vod_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vod_v1_events_proto_rawDesc), len(file_vod_v1_events_proto_rawDesc)))
	})
	return file_vod_v1_events_proto_rawDescData
}

var file_vod_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vod_v1_events_proto_goTypes = []any{
	(*VodAssemble)(nil), // 0: vod.v1.VodAssemble
	(*VodReady)(nil),    // 1: vod.v1.VodReady
}
var file_vod_v1_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vod_v1_events_proto_init() }
func file_vod_v1_events_proto_init() {
	if File_vod_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vod_v1_events_proto_rawDesc), len(file_vod_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vod_v1_events_proto_goTypes,
		DependencyIndexes: file_vod_v1_events_proto_depIdxs,
		MessageInfos:      file_vod_v1_events_proto_msgTypes,
	}.Build()
	File_vod_v1_events_proto = out.File
	file_vod_v1_events_proto_goTypes = nil
	file_vod_v1_events_proto_depIdxs = nil
}
