// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: stream/v1/events.proto

package streamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStarted) Reset() {
	*x = StreamStarted{}
	mi := &file_stream_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStarted) ProtoMessage() {}

func (x *StreamStarted) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStarted.ProtoReflect.Descriptor instead.
func (*StreamStarted) Descriptor() ([]byte, []int) {
	return file_stream_v1_events_proto_rawDescGZIP(), []int{0}
}

type StreamEnded struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEnded) Reset() {
	*x = StreamEnded{}
	mi := &file_stream_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEnded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEnded) ProtoMessage() {}

func (x *StreamEnded) ProtoReflect() protoreflect.Message {
	mi := &file_stream_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEnded.ProtoReflect.Descriptor instead.
func (*StreamEnded) Descriptor() ([]byte, []int) {
	return file_stream_v1_events_proto_rawDescGZIP(), []int{1}
}

var File_stream_v1_events_proto protoreflect.FileDescriptor

const file_stream_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x16stream/v1/events.proto\x12\tstream.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0f\n" +
	"\rStreamStarted\"\r\n" +
	"\vStreamEndedB@Z>koftamainee.dev/project-horizon/gopkg/proto/stream/v1;streamv1b\x06proto3"

var (
	file_stream_v1_events_proto_rawDescOnce sync.Once
	file_stream_v1_events_proto_rawDescData []byte
)

func file_stream_v1_events_proto_rawDescGZIP() []byte {
	file_stream_v1_events_proto_rawDescOnce.Do(func() {
		file_stream_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stream_v1_events_proto_rawDesc), len(file_stream_v1_events_proto_rawDesc)))
	})
	return file_stream_v1_events_proto_rawDescData
}

var file_stream_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stream_v1_events_proto_goTypes = []any{
	(*StreamStarted)(nil), // 0: stream.v1.StreamStarted
	(*StreamEnded)(nil),   // 1: stream.v1.StreamEnded
}
var file_stream_v1_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stream_v1_events_proto_init() }
func file_stream_v1_events_proto_init() {
	if File_stream_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stream_v1_events_proto_rawDesc), len(file_stream_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stream_v1_events_proto_goTypes,
		DependencyIndexes: file_stream_v1_events_proto_depIdxs,
		MessageInfos:      file_stream_v1_events_proto_msgTypes,
	}.Build()
	File_stream_v1_events_proto = out.File
	file_stream_v1_events_proto_goTypes = nil
	file_stream_v1_events_proto_depIdxs = nil
}
